version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_HOME_ASSISTANT_IP
      APP_PORT: 8123
      PROXY_AUTH_ADD: "false"

  server:
    image: homeassistant/home-assistant:2022.10.5@sha256:5627d0302ef3b607e31f88cb401ec6b2d1f9d45851c4d628013b010c654b547f
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - ${APP_DATA_DIR}/configuration.yaml:/config/configuration.yaml
    networks:
      default:
        ipv4_address: $APP_HOME_ASSISTANT_IP
